apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - laravel-deployment.yaml
  - laravel-service.yaml
  - nginx-configmap.yaml
  # - env-configmap.yaml
  - laravel-env.yaml
  - laravel-worker.yaml
  - laravel-ingress.yaml
  - laravel-hpa.yaml
  - laravel-worker-hpa.yaml
